# NetBox configuration for candidate C.
#
# NetBox's documented install step is `cp configuration_example.py
# configuration.py` — a file written *inside* the checkout. The spike must not
# modify the repository under test, so this uses the escape hatch NetBox
# documents at docs/configuration/index.md:10 instead: NETBOX_CONFIGURATION
# names any importable module, and PYTHONPATH can put it outside the tree.
#
# Worth noting against candidate B, which needed the same manoeuvre and had no
# such hatch. Here it is a supported feature with a documented name; there it
# was an improvisation. Same obstacle shape, very different cost.
#
# Run with:
#   PYTHONPATH=/seeds NETBOX_CONFIGURATION=spike_config_c
from __future__ import annotations

ALLOWED_HOSTS = ["*"]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "spike_c",
        "USER": "coldfix_test",
        "PASSWORD": "coldfix_test",
        "HOST": "postgres",
        "PORT": "5432",
        "CONN_MAX_AGE": 300,
    }
}

# Both sections are mandatory even though this spike exercises neither queuing
# nor caching — NetBox validates their presence at startup.
REDIS = {
    "tasks": {
        "HOST": "redis",
        "PORT": 6379,
        "USERNAME": "",
        "PASSWORD": "",
        "DATABASE": 0,
        "SSL": False,
    },
    "caching": {
        "HOST": "redis",
        "PORT": 6379,
        "USERNAME": "",
        "PASSWORD": "",
        "DATABASE": 1,
        "SSL": False,
    },
}

# Throwaway, generated by netbox/generate_secret_key.py for this spike only.
SECRET_KEY = "sxWE-m3G_T^9fNU)Rfr+Vj1^8cAdWsIliOvzRaWc1uf8+5Fs3R"

# Added only after hitting obstacle C-5. `configuration_example.py` ships this
# as `{}`, and an empty mapping is *almost* fine: NetBox starts, and emits a
# UserWarning buried in migration output saying v2 API tokens cannot be used.
# It becomes a hard ValueError at the moment you create a token — i.e. at the
# one step that stands between a grounded database and a driveable API.
# Peppers must be at least 50 characters.
API_TOKEN_PEPPERS = {
    1: "spike-only-pepper-not-a-secret-0123456789-0123456789-0123456789",
}
